### PR TITLE
Karr/calib proto

### PR DESCRIPTION
**Pull request by JenniferKarr**
Update which 
  - generates prototypes for the external calibration files
  - contains a minimal set of SOF files for all recipes
  - has a few minor bug fixes and updates

### CODE REVIEW

**Review by hugobuddel — APPROVED** [review]
Great! Now we have all the pieces of the puzzle, thanks!

I didn't go through everything in makeCalibPrototypes.py, so I'll trust you that it is okay, and we can fix anything later.

I was not aware one can use asterisks in SOF files, but maybe we can. Otherwise we will know soon enough :-).

**Comment by JenniferKarr** [comment]
Regarding the asterisks, those are a hack for generating sof files without having to redo them manually if the file names change (and without recreating the EDPS header parsing system). The script reads in the templates, grabs the relevant RAW files by DO.CATG if there is an asterisk in the file name, and writes the output files; after that there's about five minutes of tidying.

**Comment by JenniferKarr** [comment]
Added SOF files and prototypes for the external calibration files. SOF files in sofFiles/ match the simulated images in output/  and have the filename of the recipes. 

Note that the actual tags in the SOF files can be anything (as set by the workflow); I've used the DO.CATG/PRO.CATG as given in the DRLD as the defaults. It's probably simpler to stick with these until the automatic generation of SOF files is working.

**Comment by hugobuddel** [comment]
Yeah the idea behind the DO.CATG values is to use them as tags in the SOF files for the recipes. In fact, the DO.CATG is a transient 'thing' used exactly for that purpose by the OCA rules, a predecessor of the EDPS. So we should use those values in the recipes too, that is why they are in the DRLD.

**Comment by hugobuddel** [comment]
It seemed you accidentally closed this instead of merging it, so I took the liberty to merge it anyway.

**Pull request merged**
